---
kind: pipeline
name: build
type: kubernetes

resources:
  requests:
    memory: 128Mi

steps:
- name: image
  image: plugins/docker
  pull: always
  settings:
    repo: ghcr.io/rkojedzinszky/docker-registry-auth
    registry: ghcr.io
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    auto_tag: true
    auto_label: false
    mirror:
      from_secret: hub_docker_mirror

  privileged: true
  volumes:
    - name: docker
      path: /var/lib/docker

volumes:
  - name: docker
    temp: {}

depends_on:
  - integration tests
