kind: pipeline
name: integration tests
type: kubernetes

trigger:
  branch:
    - master

steps:
  - name: integration tests
    image: alpine:3.14
    pull: always
    commands:
      - apk add --no-cache python3 py3-pip openssl supervisor nginx py3-psycopg2 uwsgi-python3 py3-cryptography py3-jwt
      - pip3 install -r requirements.txt
      - DBHOST=127.0.0.1 python3 manage.py test

services:
  - name: postgres
    image: postgres:11
    environment:
      POSTGRES_USER: dra
      POSTGRES_PASSWORD: dra
