# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dra', '0001_initial_20161031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, to='dra.Group'),
        ),
    ]
