# Generated by Django 2.2.7 on 2020-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dra', '0003_repository_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='requests',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='requests',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorypermissions',
            name='requests',
            field=models.BigIntegerField(default=0),
        ),
    ]
