# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 08:31
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User as djangoUserModel, Group as djangoGroupModel

def migrate_groups(apps, schema_editor):
    GroupModel = apps.get_model('dra', 'Group')

    for g in djangoGroupModel.objects.all():
        GroupModel.objects.create(name=g.name)

def migrate_accounts(apps, schema_editor):
    AccountModel = apps.get_model('dra', 'Account')

    for u in djangoUserModel.objects.all():
        AccountModel.objects.create(username=u.username, password=u.password)

def migrate_group_memberships(apps, schema_editor):
    AccountModel = apps.get_model('dra', 'Account')
    GroupModel = apps.get_model('dra', 'Group')

    for u in djangoUserModel.objects.all():
        a = AccountModel.objects.get(username=u.username)
        a.groups = [GroupModel.objects.get(name=g.name) for g in u.groups.all()]

def update_repository_permissions(apps, schema_editor):
    RepositoryPermissionsModel = apps.get_model('dra', 'RepositoryPermissions')
    GroupModel = apps.get_model('dra', 'Group')

    for r in RepositoryPermissionsModel.objects.select_related('sgroup'):
        r.group = GroupModel.objects.get(name=r.sgroup.name)
        r.sgroup = None
        r.save()

def remove_non_admin_accounts(apps, schema_editor):
    djangoUserModel.objects.filter(is_superuser=False).delete()

def remove_django_groups(apps, schema_editor):
    djangoGroupModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('dra', '0003_auto_20161031_0824'),
    ]

    operations = [
            migrations.RunPython(migrate_groups),
            migrations.RunPython(migrate_accounts),
            migrations.RunPython(migrate_group_memberships),
            migrations.RunPython(update_repository_permissions),
            migrations.RunPython(remove_non_admin_accounts),
            migrations.RunPython(remove_django_groups),
    ]
