# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dra', '0004_data_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorypermissions',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dra.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='repositorypermissions',
            unique_together=set([('repository', 'group')]),
        ),
        migrations.RemoveField(
            model_name='repositorypermissions',
            name='sgroup',
        ),
    ]
